### PR TITLE
fix: color change persistence

### LINKED ISSUE #1: Color picker persistence
As you can see in the gif color picker works well changing from black to brown but as soon as I change the grid size, the color picker shows brown color but the actual color changes to black.

aaag(before)

### PR DESCRIPTION
**Pull request by shreyshreyansh**
Resolves #1 

Before

aaag(before)

After

aaa(after)

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -1,111 +1,119 @@
...
-chooseColor.addEventListener('input', function(){
-    let val = document.getElementById('slider').value;
-    let newColor = document.getElementById('color').value;
-    let cell = grid.children;
-    for (let i = 0; i < val*val; i++) {
-        cell[i].addEventListener('mouseover', function(event){
-            event.target.style.backgroundColor = newColor;
-        })
-    }
+document.addEventListener("color", function (e) {
```
Comment (shreyshreyansh) [inline app.js:108]: added an event listener, if there is a change in grid. The color persists.

**Comment by priyanshk20** [comment]
Thank you so much!
